### ISSUE TITLE
Flood crash on login

### ISSUE THREAD

**Issue by kumy** [binhex/arch-rtorrentvpn#98]
After updating to latest, flood crash when authenticating. I've launched it manually in the container:

```
# node server/bin/start.js /etc/webapps/flood
Migrating data: moving rTorrent connection information to users database
Migrating data: resolving unset isAdmin flag
Flood server starting on http://0.0.0.0:3000.

GET /api/activity-stream?historySnapshot=fiveMin 401 4.367 ms - -
GET /login 200 7.991 ms - 543
GET /static/css/main.16a9269d.css 200 5.310 ms - -
GET /static/js/main.ef1b8922.js 200 1.265 ms - -
GET /api/activity-stream?historySnapshot=fiveMin 401 0.596 ms - -
GET /auth/verify?1550865195718 401 7.909 ms - -
GET /static/media/Roboto-700.3b38c16e.woff2 200 4.415 ms - 10276
GET /static/media/Roboto-500.1afbee5a.woff2 200 3.455 ms - 10248
GET /static/media/Roboto-regular.f84cb1bf.woff2 200 3.375 ms - 10292
GET /favicon.ico 200 1.593 ms - -
GET /static/css/main.16a9269d.css.map 200 0.924 ms - -
/etc/webapps/flood/node_modules/argon2/argon2.js:89
      m: memoryCost, t: timeCost, p: parallelism
      ^

TypeError: Cannot destructure property `m` of 'undefined' or 'null'.
    at Object.verify (/etc/webapps/flood/node_modules/argon2/argon2.js:91:7)
    at db.findOne.exec (/etc/webapps/flood/server/models/Users.js:36:10)
    at newArguments.(anonymous function) (/etc/webapps/flood/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/etc/webapps/flood/node_modules/nedb/lib/datastore.js:518:14)
    at callback (/etc/webapps/flood/node_modules/nedb/lib/cursor.js:126:19)
    at /etc/webapps/flood/node_modules/nedb/lib/cursor.js:193:12
    at /etc/webapps/flood/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/etc/webapps/flood/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /etc/webapps/flood/node_modules/nedb/lib/datastore.js:323:11
    at fn (/etc/webapps/flood/node_modules/nedb/node_modules/async/lib/async.js:582:34)
```

Any clue on what's going wrong? Thanks

**Comment by GottZ** [comment]
thats related to the password hashing function (checking if your password is correct)
i have the same problem.
i just removed the auth check aince i have it behind my own authenticator though.. it worked but flood still stayed kinda unstable and the rss feeds were not present anymore.
i simply decided not to use flood anymore.
back to rutorrent until flood is better maintained.

**Comment by kumy** [comment]
I've also switched back temporarily to rutorrent…

**Comment by binhex** [comment]
if there are fundamental issues like this with flood i would encourage you to post these as 'issues' on the flood github repo so the developer can fix them up.

**Comment by kumy** [comment]
FTR: reinstalling from scratch solved my issue ;)
